service: hyperlocal-auction-service
frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  region: ca-central-1
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    AUCTIONS_TABLE_NAME: ${self:custom.HyperlocalAuctionsTable.name}
  iam:
    role:
      statements:
        - ${file(iam/HyperlocalAuctionsTableIAM.yml):HyperlocalAuctionsTableIAM}

resources:
  Resources:
    HyperlocalAuctionsTable: ${file(resources/HyperlocalAuctionsTable.yml):HyperlocalAuctionsTable}

functions:
  createAuction:
    handler: src/handlers/createAuction.handler
    events:
      - http:
          method: POST
          path: /auctions
  getAuctions:
    handler: src/handlers/getAuctions.handler
    events:
      - http:
          method: GET
          path: /auctions
  getAuction:
    handler: src/handlers/getAuction.handler
    events:
      - http:
          method: GET
          path: /auctions/{id}
  placeBid:
    handler: src/handlers/placeBid.handler
    events:
      - http:
          method: PATCH
          path: /auctions/{id}/bid
  processAuctions:
    handler: src/handlers/processAuctions.handler
    # events:
    #   - schedule: rate(1 minute)

package:
  individually: true

custom:
  HyperlocalAuctionsTable:
    name: !Ref HyperlocalAuctionsTable
    arn: !GetAtt HyperlocalAuctionsTable.Arn
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: 'node18'
    platform: 'node'
    concurrency: 10
