service: hyperlocal-notification-service
frameworkVersion: "3"
useDotenv: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  region: ca-central-1
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  iam:
    role:
      statements:
        - ${file(iam/HyperlocalSendMailIAM.yml):HyperlocalSendMailIAM}

  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: "1"
    NODE_OPTIONS: "--enable-source-maps --stack-trace-limit=1000"
    SECRET_MESSAGE: ${env:SECRET_MESSAGE}

resources:
  Resources:
    HyperlocalMailQueue: ${file(resources/HyperlocalMailQueue.yml):HyperlocalMailQueue}
  Outputs:
    HyperlocalMailQueueArn: ${file(resources/HyperlocalMailQueue.yml):Outputs.HyperlocalMailQueueArn}
    HyperlocalMailQueueUrl: ${file(resources/HyperlocalMailQueue.yml):Outputs.HyperlocalMailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.HyperlocalMailQueue.arn}
          batchSize: 1

package:
  individually: true

custom:
  HyperlocalMailQueue:
    name: HyperlocalMailQueue-${self:provider.stage}
    arn: !GetAtt HyperlocalMailQueue.Arn
    url: !Ref HyperlocalMailQueue
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: "node18"
    platform: "node"
    concurrency: 10
