service: hyperlocal-notification-service
frameworkVersion: '3'

plugins:
  - serverless-esbuild

provider:
  name: aws
  region: ca-central-1
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
  iam:
    role:
      statements:
        - ${file(iam/SendMailIAM.yml):SendMailIAM}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler

package:
  individually: true

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: 'node18'
    platform: 'node'
    concurrency: 10
