service: hyperlocal-community-service
frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  region: ca-central-1
  runtime: nodejs18.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    COMMUNITIES_TABLE_NAME: ${self:custom.CommunitiesTable.name}
  iam:
    role:
      statements:
        - ${file(iam/CommunitiesTableIAM.yml):CommunitiesTableIAM}

resources:
  Resources:
    CommunitiesTable: ${file(resources/CommunitiesTable.yml):CommunitiesTable}

functions:
  createCommunity:
    handler: src/handlers/createCommunity.handler
    events:
      - http:
          method: POST
          path: /communities
  getCommunity:
    handler: src/handlers/getCommunity.handler
    events:
      - http:
          method: GET
          path: /communities/{id}
  getCommunities:
    handler: src/handlers/getCommunities.handler
    events:
      - http:
          method: GET
          path: /communities
  updateCommunity:
    handler: src/handlers/updateCommunity.handler
    events:
      - http:
          method: PUT
          path: /communities/{id}
  deleteCommunity:
    handler: src/handlers/deleteCommunity.handler
    events:
      - http:
          method: DELETE
          path: /communities/{id}

package:
  individually: true

custom:
  CommunitiesTable:
    name: !Ref CommunitiesTable
    arn: !GetAtt CommunitiesTable.Arn
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: 'node18'
    platform: 'node'
    concurrency: 10
